---
output: 
  pdf_document:
    fig_crop: no
#bibliography: "referencias.bib"
#nocite: '@*'
#link-citations: true
#colorlinks: false
fontsize: 11pt
documentclass: article
geometry: 
 - a4paper
 - textwidth=16cm
 - textheight=21cm
header-includes:
  - \usepackage[brazil, english, portuguese]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage[fixlanguage]{babelbib}
  - \usepackage{times}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
  - \usepackage{amsmath}
  - \usepackage{float}
  - \usepackage{indentfirst}
indent: true
---

```{=tex}
\begin{titlepage} 
\begin{center} 
{\large Universidade Estadual de Campinas}\\[0.2cm] 
{\large Instituto de Matemática, Estatística e Computação Científica}\\[0.2cm] 
{\large Departamento de Estatística}\\[4cm]
{\bf \huge  Atividade 3 - ME721}\\[0.9cm]
{\large Integrantes:}\\[0.2cm]
{\large Rodrigo Forti - 224191}\\[0.2cm]
{\large João Pedro Shimizu Rodrigues - 218793}\\[0.2cm]
{\large Guilherme Martins de Castro Gurgel - 217249}\\[10cm]
{\large Campinas}\\[0.2cm]
{\large 2021}
\end{center}
\end{titlepage}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 4, 
                      fig.width = 7, 
                      fig.pos='H',
                      OutDec = ',',
                      #out.extra = '',
                      comment = NA)
options(OutDec = ",")
```

```{r}
#Pacotes
library(tidyverse)
library(kableExtra)
library(knitr)
library(patchwork)
```

# Estado escolhido: Minas Gerais (MG)

```{r carregando os dados}
mg_pop_1980 = read_delim("pop_1980_MG.csv",skip = 3,delim = ";",n_max = 12);#mg_pop_1980
mg_pop_2010 =read_delim("pop_2010_MG.csv",skip = 3,delim = ";",n_max = 12);#mg_pop_2010
mg_morte_1980 = read_delim("mort_1980_MG.csv",skip = 3,delim = ";",n_max = 12) %>% select(-Ign); #mg_morte_1980
mg_morte_2010 = read_delim("mort_2010_MG.csv",skip = 3,delim = ";",n_max = 12) %>% select(-Ign); #mg_morte_2010

nomes = c("faixa","masc","femi","total")

colnames(mg_pop_1980) = nomes
colnames(mg_pop_2010) = nomes
colnames(mg_morte_1980) = nomes
colnames(mg_morte_2010) = nomes

```

## Questão 1

## Questão 2

## Questão 3

## Questão 4