---
title: "Atividade 1 - ME721"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r, Leitura e definição dos dados ceará 1980}
path_df_idade80 = 'A171441189_28_143_208.csv'
df_idade80 = read.csv(path_df_idade80,sep=';', skip=3, nrows=33, header=T)
colnames(df_idade80)[1] <- 'Faixa.Etária.detalhada'

df_idade80 = as_tibble(df_idade80) %>% select(-Total)

df_idade_juntas80 = df_idade80[21:nrow(df_idade80),]
inicio = 1
fim = 5

for (i in 1:4){
  idades_juntas = c("0 a 4 anos",
                    "5 a 9 anos",
                    "10 a 14 anos",
                    "15 a 19 anos")
  idade_masc = df_idade80[inicio:fim,] %>% select(Masculino) %>% colSums() %>% as.vector()
  idade_fem = df_idade80[inicio:fim,] %>% select(Feminino) %>% colSums() %>% as.vector()
  df_idade_juntas80 = rbind(df_idade_juntas80,c(idades_juntas[i],idade_masc, idade_fem))
  inicio = inicio + 5
  fim = fim + 5
  #i = i + 1
}

df_80 = df_idade_juntas80 

df_80 = df_80 %>% gather("sexo","n_pessoas",2:3)

inicio = 0 
fim = 4
nomes_idades = NULL

for (i in 1:17){
  nomes_idades =  c(nomes_idades,paste0(inicio," a ",fim, ' anos'))
  inicio = inicio + 5
  fim = fim + 5
}

nomes_idades[length(nomes_idades)] = '80 anos e mais'

df_80$Faixa.Etária.detalhada = as.factor(df_80$Faixa.Etária.detalhada)

df_80$Faixa.Etária.detalhada = factor(df_80$Faixa.Etária.detalhada, levels = nomes_idades)

df_80$sexo = as.factor(df$sexo)
df_80$n_pessoas = as.numeric(df$n_pessoas)

df_80 = df_80 %>% mutate(perc_pop = if_else(sexo  == 'Masculino', -n_pessoas/sum(df_80$n_pessoas), n_pessoas/sum(df_80$n_pessoas)))
```

```{r, Leitura e definição dos dados ceará 2010}
path_df_idade10 = 'Ceara2010.csv'
df_idade10 = read.csv(path_df_idade10,sep=';', skip=3, nrows=33, header=T)
colnames(df_idade10)[1] <- 'Faixa.Etária.detalhada'

df_idade10 = as_tibble(df_idade10) %>% select(-Total)

df_idade_juntas10 = df_idade10[21:nrow(df_idade10),]
inicio = 1
fim = 5

for (i in 1:4){
  idades_juntas10 = c("0 a 4 anos",
                    "5 a 9 anos",
                    "10 a 14 anos",
                    "15 a 19 anos")
  idade_masc = df_idade10[inicio:fim,] %>% select(Masculino) %>% colSums() %>% as.vector()
  idade_fem = df_idade10[inicio:fim,] %>% select(Feminino) %>% colSums() %>% as.vector()
  df_idade_juntas10 = rbind(df_idade_juntas10,c(idades_juntas10[i],idade_masc, idade_fem))
  inicio = inicio + 5
  fim = fim + 5
  i = i + 1
}

df10 = df_idade_juntas10 

df10 = df10 %>% gather("sexo","n_pessoas",2:3)

df10$Faixa.Etária.detalhada = as.factor(df10$Faixa.Etária.detalhada)

df10$Faixa.Etária.detalhada = factor(df10$Faixa.Etária.detalhada, levels = nomes_idades)

df10$sexo = as.factor(df10$sexo)
df10$n_pessoas = as.numeric(df10$n_pessoas)

df10 = df10 %>% mutate(perc_pop = if_else(sexo  == 'Masculino', -n_pessoas/sum(df10$n_pessoas), n_pessoas/sum(df10$n_pessoas)))
```

# Exercício 1
```{r, piramide etaria 1980}
df_80 %>% ggplot(
    aes(x = Faixa.Etária.detalhada,
        y = perc_pop, fill = sexo)
    ) +
  # agregar el argumento color = "white", si gustan
    geom_col(position = "stack", alpha = 0.6) + 
    coord_flip() +
  # colores que me gustan
    scale_fill_manual(values = c("midnightblue", "darkred")) +
  # tema minimalista
    theme_minimal() +
  # leyenda para el fondo
    theme(
      legend.position = "bottom",
      plot.caption = element_text(hjust = 0)) +
  # etiquetas en positivo
    scale_y_continuous(labels = abs) +
    labs(
      y = "Porcentagem da população",
      x = "Faixas etárias",
      title = "Pirâmide etária do Estado do Ceará, ano 1980"
      #subtitle = "Edad en grupos quinquenales"
      )
```

```{r, piramide etaria 2010}
df10 %>% ggplot(
    aes(x = Faixa.Etária.detalhada,
        y = perc_pop, fill = sexo)
    ) +
  # agregar el argumento color = "white", si gustan
    geom_col(position = "stack", alpha = 0.6) + 
    coord_flip() +
  # colores que me gustan
    scale_fill_manual(values = c("midnightblue", "darkred")) +
  # tema minimalista
    theme_minimal() +
  # leyenda para el fondo
    theme(
      legend.position = "bottom",
      plot.caption = element_text(hjust = 0)) +
  # etiquetas en positivo
    scale_y_continuous(labels = abs) +
    labs(
      y = "Porcentagem da população",
      x = "Faixas etárias",
      title = "Pirâmide etária do Estado do Ceará, ano 2010"
      #subtitle = "Edad en grupos quinquenales"
      )
```

# Exercício 2
```{r}
#1980
df_idade_juntas80$Faixa.Etária.detalhada = as.factor(df_idade_juntas80$Faixa.Etária.detalhada)

df_idade_juntas80$Faixa.Etária.detalhada = factor(df_idade_juntas80$Faixa.Etária.detalhada, levels = nomes_idades)

df_idade_juntas80[order(df_idade_juntas80$Faixa.Etária.detalhada),] %>%
  mutate(r_sexos = as.double(Masculino)/as.double(Feminino)) %>%
  ggplot(aes(x = seq(1,nrow(df_idade_juntas80)),
             y = r_sexos)) +
  geom_line() +
  scale_x_continuous(breaks = 1:(nrow(df_idade_juntas80)),
    labels = levels(df_idade_juntas80$Faixa.Etária.detalhada))+
  geom_abline(intercept = 1, slope = 0) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  # leyenda para el fondo
    theme(
      legend.position = "bottom",
      plot.caption = element_text(hjust = 0))+
  labs(
      y = "Razão entre os sexos",
      x = "Faixas etárias",
      title = "Razão entre os sexos no Estado do Ceará, ano 1980"
      #subtitle = "Edad en grupos quinquenales"
      )
  
```

```{r}
#1980
df_idade_juntas10$Faixa.Etária.detalhada = as.factor(df_idade_juntas80$Faixa.Etária.detalhada)

df_idade_juntas10$Faixa.Etária.detalhada = factor(df_idade_juntas10$Faixa.Etária.detalhada, levels = nomes_idades)

df_idade_juntas10[order(df_idade_juntas80$Faixa.Etária.detalhada),] %>%
  mutate(r_sexos = as.double(Masculino)/as.double(Feminino)) %>%
  ggplot(aes(x = seq(1,nrow(df_idade_juntas10)),
             y = r_sexos)) +
  geom_line() +
  scale_x_continuous(breaks = 1:(nrow(df_idade_juntas10)),
    labels = levels(df_idade_juntas10$Faixa.Etária.detalhada))+
  geom_abline(intercept = 1, slope = 0) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  # leyenda para el fondo
    theme(
      legend.position = "bottom",
      plot.caption = element_text(hjust = 0))+
  labs(
      y = "Razão entre os sexos",
      x = "Faixas etárias",
      title = "Razão entre os sexos no Estado do Ceará, ano 2010"
      #subtitle = "Edad en grupos quinquenales"
      )
```


# Exercício 3
Primeiramente, calculando a taxa de crescimento geometrica entre os anos 1980 e 2010 no Ceara

```{r}
#Lendo os dados

Ceara1980 = read.csv("A171441189_28_143_208.csv", sep=';', skip=4, nrows=33, header=F)

Ceara2010 = read.csv("Ceara2010.csv", sep=';', skip=4, nrows=33, header=F)
```

```{r}
#Colocando nomes apropriados para as colunas

colnames(Ceara1980)=c('Idade','Masculino','Feminino','Total') 

colnames(Ceara2010)=c('Idade','Masculino','Feminino','Total') 
```

```{r}
#Calculando a populacao total do Ceara em 1980 e em 2010

pop1980 = sum(Ceara1980$Total)

pop2010 = sum(Ceara2010$Total)
```


```{r}
#Formula para Taxa de Crescimento Geometrica: (raiz(n)(Pt/P0)-1)*100 onde n = 30 (Diferenca entre os anos 1980 e 2010)

Taxa_Crescimento_Geometrica = (((pop2010/pop1980)^(1/30))-1)*100

Taxa_Crescimento_Geometrica
```

Agora, calculando a razao de dependencia de cada ano para jovens e idosos

```{r}
#Colocando os intervalos de idade nas linhas

rownames(Ceara1980) = Ceara1980$Idade

Ceara1980 = Ceara1980[,-1]

rownames(Ceara2010) = Ceara2010$Idade

Ceara2010 = Ceara2010[,-1]
```


```{r}
#Criando grupos de idade para agrupar as idades simples

grupo_idade=cut(rep(0:32),breaks=c(0,0.99,4,9,14,19,20,21,22,23,24,25,26,27,28,29,30,31,32),include.lowest = T)

Ceara1980.n=aggregate(Ceara1980,list(Idade=grupo_idade),sum)

Ceara2010.n=aggregate(Ceara2010,list(Idade=grupo_idade),sum)
```


```{r}
#Representando os intervalos de idade em apenas um numero

Ceara1980.n$Idade=c(0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80)

Ceara2010.n$Idade=c(0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80)
```


```{r}
#Razao de dependencia para os jovens do Ceara em 1980

Jovens1980 = with(Ceara1980.n, sum(Ceara1980.n[Ceara1980.n$Idade<15,4]))

pop.ativa1980 = with(Ceara1980.n, sum(Ceara1980.n[Ceara1980.n$Idade>10 & Idade<65,4]))

RD.jovens1980 = (Jovens1980/pop.ativa1980)*100

RD.jovens1980
```

```{r}
#Razao de dependencia para os idosos do Ceara em 1980

Idosos1980=with(Ceara1980.n, sum(Ceara1980.n[Ceara1980.n$Idade>64,4]))

RD.Idosos1980 = (Idosos1980/pop.ativa1980)*100

RD.Idosos1980
```

```{r}
#Razao de dependencia para os jovens do Ceara em 2010

Jovens2010 = with(Ceara2010.n, sum(Ceara2010.n[Ceara2010.n$Idade<15,4]))

pop.ativa2010 = with(Ceara2010.n, sum(Ceara2010.n[Ceara2010.n$Idade>10 & Idade<65,4]))

RD.jovens2010 = (Jovens2010/pop.ativa2010)*100

RD.jovens2010
```

```{r}
#Razao de dependencia para os idosos do Ceara em 1980

Idosos2010 = with(Ceara2010.n, sum(Ceara2010.n[Ceara2010.n$Idade>64,4]))

RD.Idosos2010 = (Idosos2010/pop.ativa2010)*100

RD.Idosos2010
```