---
output: 
  pdf_document:
    fig_crop: no
#bibliography: "referencias.bib"
#nocite: '@*'
#link-citations: true
#colorlinks: false
fontsize: 11pt
documentclass: article
geometry: 
 - a4paper
 - textwidth=16cm
 - textheight=21cm
header-includes:
  - \usepackage[brazil, english, portuguese]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage[fixlanguage]{babelbib}
  - \usepackage{times}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
  - \usepackage{amsmath}
  - \usepackage{float}
  - \usepackage{indentfirst}
indent: true
---

```{=tex}
\begin{titlepage} 
\begin{center} 
{\large Universidade Estadual de Campinas}\\[0.2cm] 
{\large Instituto de Matemática, Estatística e Computação Científica}\\[0.2cm] 
{\large Departamento de Estatística}\\[4cm]
{\bf \huge  Atividade 2 - ME721}\\[0.9cm]
{\large Integrantes:}\\[0.2cm]
{\large Rodrigo Forti - 224191}\\[0.2cm]
{\large João Pedro Shimizu Rodrigues - 218793}\\[0.2cm]
{\large Guilherme Martins de Castro Gurgel - 217249}\\[10cm]
{\large Campinas}\\[0.2cm]
{\large 2021}
\end{center}
\end{titlepage}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 4, 
                      fig.width = 7, 
                      fig.pos='H',
                      OutDec = ',',
                      #out.extra = '',
                      comment = NA)
options(OutDec = ",")
```

```{r}
#Pacotes
library(tidyverse)
```

```{r}
#Carregando os dados
rs_pop_2000 = read_delim("RS_popresidente_2000.csv",skip = 3,delim = ";",n_max = 33)
rs_pop_2010 = read_delim("RS_popresidente_2010.csv",skip = 3,delim = ";",n_max = 33)
rs_nasc_datasus_2000 = read_delim("RS_Nascimentos_2000.csv",skip = 3,delim = ";",n_max = 10)
rs_nasc_datasus_2010 = read_delim("RS_Nascimentos_2010.csv",skip = 3,delim = ";",n_max = 10)
rs_nasc_sidra_2000 = read_delim("rs_nasc_sidra_2000.csv", delim = ',', col_names = FALSE, na = '-')
rs_nasc_sidra_2010 = read_delim("rs_nasc_sidra_2010.csv", delim = ';', col_names = FALSE, na = '-')

#Nome das colunas
colnames(rs_nasc_sidra_2000) = c("UF","Total","Idade","Nasc")
colnames(rs_nasc_sidra_2010) = c("UF","Total","Idade","Nasc")
rs_nasc_sidra_2000 = rs_nasc_sidra_2000 %>% dplyr::select(Idade,Nasc)
rs_nasc_sidra_2010 = rs_nasc_sidra_2010 %>% dplyr::select(Idade,Nasc)
colnames(rs_nasc_datasus_2000) = c("Idade","Nasc")
colnames(rs_nasc_datasus_2010) = c("Idade","Nasc")
colnames(rs_pop_2000) = c("Idade","Masc","Femi","Total")
colnames(rs_pop_2010) = c("Idade","Masc","Femi","Total")
```

# Estado escolhido: Estado do Rio Grande do Sul (RS)

## Exercício 1

$ \frac{\text{#filhos de residentes nascidos vivos neste ano}}{\text{#residentes neste ano}} $
```{r}
#Taxa Bruta de Natalidade
n2000 <- sum(rs_pop_2000$Total); n2010 <- sum(rs_pop_2010$Total)
tab1 <- data.frame(Datasus = c(sum(rs_nasc_datasus_2000$Nasc)/n2000 * 1000, sum(rs_nasc_datasus_2010$Nasc)/n2010 * 1000),
Sidra = c(sum(rs_nasc_sidra_2000$Nasc[c(1:12)])/n2000 * 1000, sum(rs_nasc_sidra_2010$Nasc)/n2010 * 1000))
rownames(tab1) <- c('2000','2010')
tab1 %>% round(3)
```


## Exercício 2

$ \frac{\text{#filhos de residentes nascidos vivos neste ano}}{\text{#mulheres entre 15 e 49 anos}} $
```{r}
#Taxa de Fecundidade Geral
n2000 <- sum(rs_pop_2000$Total[c(16:26)]); n2010 <- sum(rs_pop_2010$Total[c(16:26)])
tab2 <- data.frame(Datasus = c(sum(rs_nasc_datasus_2000$Nasc)/n2000, sum(rs_nasc_datasus_2010$Nasc)/n2010),
Sidra = c(sum(rs_nasc_sidra_2000$Nasc[c(1:12)])/n2000, sum(rs_nasc_sidra_2010$Nasc)/n2010))
rownames(tab2) <- c('2000','2010')
tab2 %>% round(3)
rs_pop_2000
```

## Exercício 3

## Exercício 4